@startuml

Title: Hello World App Sequence Diagram

actor "User" as U
participant "Browser" as B
participant "UI Layer" as UI
participant "REST API" as RA
participant "Database" as DB

U -> B: Navigate\nhomepage
B -> UI: GET /hello/welcome
UI -> B: Return page
B -> B: Execute Javascript
B -> RA: GET /hello/welcome
RA -> DB:Query table\nfor key "welcome"
DB -> RA:Return value "Hello World!"
|||
RA -> B:Response 200 OK
note right
response format:
{"test":<text-from-db>}
end note
B -> U: Render\nwelcome message
||45||

@enduml 